### ISSUE TITLE
This doesn't work when you click on child elements of anchors

### ISSUE THREAD

**Issue by PF2M** [ariankordi/light-pjax#1]
Here's a bit of HTML:
```html
<div id="sidebar">
    <a href="/">
        <span class="icon home"></span> Home
    </a>
</div>
```
Now, when I run pjax.listen(), it runs properly when you click "Home", but not the icon next to it. To verify this, you can put that in a `<span>` as well:
```html
<div id="sidebar">
    <a href="/">
        <span class="icon home"></span>
        <span class="sidebar-item-text">Home</span>
    </a>
</div>
```
Now there's nothing you can click to trigger pjax, unless you were to click the space in the middle or something like that. I'm assuming this could be fixed by checking whether the event.target passed to linkClickFunc is an <a> element and looking for parents that are <a> elements if it isn't, but I don't know, I'm not the #1 Miiverse hacker and clone developer here.

**Comment by ariankordi** [comment]
I found that, when you click on something nested in an anchor, that the thing nested in the anchor itself becomes `event.target`, but the actual anchor stays in `event.currentTarget`, so..
```html
<a href="/yeet"> <--- currentTarget
     [<span>goto yeet</span>] <--- target
</a>
```
Since `linkClickFunc` uses event.target, it doesn't work. I've changed it to use currentTarget though, so go ahead and see if it works now, since I've only tested it with that specific HTML up there.

**Comment by ariankordi** [comment]
gosh darned git
